package chess;

public enum Figuren 
{
	WEISSERSPRINGER,WEISSERTURM,WEISSERKOENIG,WEISSEDAME,WEISSERBAUER,WEISSERLAEUFER,
	SCHWARZERSPRINGER,SCHWARZERLAEUFER,SCHWARZERKOENIG,SCHWARZEDAME,SCHWARZERBAUER,SCHWARZERTURM;
	
	public FigurenFarbe gibFigurenFarbe()
	{
		switch(this)
		{
		case SCHWARZERSPRINGER, SCHWARZERLAEUFER, SCHWARZERKOENIG,SCHWARZEDAME, SCHWARZERTURM, SCHWARZERBAUER:
			return FigurenFarbe.SCHWARZ;
		default: return FigurenFarbe.WEISS;
		}
	}
	
	public FigurenArt gibFigurenArt()
	{
		switch(this)
		{
		case WEISSERKOENIG, SCHWARZERKOENIG:
			return FigurenArt.KOENIG;
		case WEISSERLAEUFER, SCHWARZERLAEUFER:
			return FigurenArt.LAEUFER;
		case WEISSEDAME, SCHWARZEDAME:
			return FigurenArt.DAME;
		case WEISSERSPRINGER, SCHWARZERSPRINGER:
			return FigurenArt.SPRINGER;
		case WEISSERTURM, SCHWARZERTURM:
			return FigurenArt.TURM;
		case WEISSERBAUER, SCHWARZERBAUER:
			return FigurenArt.BAUER;
		default:
			return null;
		
		}
	}
}
