package chess;

public enum Figuren 
{
	WEISSERSPRINGER,WEISSERTURM,WEISSERKOENIG,WEISSEDAME,WEISSERBAUER,WEISSERLAEUFER,
	SCHWARZERSPRINGER,SCHWARZERLAEUFER,SCHWARZERKOENIG,SCHWARZEDAME,SCHWARZERBAUER,SCHWARZERTURM
	
}
